[package]
name = "advent_of_code_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
seq-macro = "0.3.5"
aoc-macro = { path = "./aoc-macro" }

[lints.rust]
dead_code = "allow"
unused_variables = "allow"
unused_imports = "allow"
